export const Status = {
  IN_POMODORO: 'in_pomodoro',
  ON_BREAK: 'on_break',
  STOPPED: 'stopped'
};

export const DefaultTimeLengths = {
  POMODORO: 25 * 60 * 1000,
  SHORT_BREAK: 5 * 1000,
  LONG_BREAK: 15  * 60 * 1000
};

export const ActionTypes = {
  POMODORO_STATUS_CHANGED: 'POMODORO_STATUS_CHANGED',
  POMODORO_TICKED: 'POMODORO_TICKED',
  REMOTE_CLIENT_REMOVED: 'REMOTE_CLIENT_REMOVED',
  REMOTE_STATUS_CHANGED: 'REMOTE_STATUS_CHANGED',
  REMOTE_SESSION_UPDATED: 'REMOTE_SESSION_UPDATED',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_UPDATED: 'SESSION_UPDATED'
};